# Generated by Django 3.1.2 on 2020-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='', max_length=200)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(default='', max_length=200)),
                ('stock', models.BooleanField(default=False)),
                ('marca', models.CharField(default='', max_length=200)),
                ('imagen', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
